[package]
name = "lyfcal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
eframe = "0.28"
egui_extras = { version = "0.28", features = ["datepicker"] }
egui = "0.28"
image = { version = "0.25", features = ["jpeg", "png"] }
