[package]
name = "lyfcal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
eframe = "0.27"
egui_extras = { version = "0.27", features = ["datepicker"] }
egui_wgpu_backend = "0.29"
egui_winit_platform = "0.22"
egui = "0.27"
pixels = "0.13"
wgpu = "0.20"
winit = "0.26"
